export interface SmashObject {
  id: string;
  name: string;
  emoji: string;
  category: 'glass' | 'wood' | 'ceramic' | 'metal' | 'electronic' | 'misc';
  hitPoints: number;
  satisfactionRating: number; // 1-5
  shardCount: number;
  description: string;
  color: string;
  secondaryColor: string;
  size: 'small' | 'medium' | 'large';
  unlockLevel: number;
}

export const SMASH_OBJECTS: SmashObject[] = [
  {
    id: 'plate',
    name: 'Dinner Plate',
    emoji: '🍽️',
    category: 'ceramic',
    hitPoints: 1,
    satisfactionRating: 3,
    shardCount: 8,
    description: 'A classic. One good smash and it shatters beautifully.',
    color: '#ddd5c7',
    secondaryColor: '#ffffff',
    size: 'medium',
    unlockLevel: 1,
  },
  {
    id: 'wine_glass',
    name: 'Wine Glass',
    emoji: '🍷',
    category: 'glass',
    hitPoints: 1,
    satisfactionRating: 4,
    shardCount: 12,
    description: 'Delicate, elegant, and extremely satisfying to destroy.',
    color: '#88ccff',
    secondaryColor: '#aaddff',
    size: 'small',
    unlockLevel: 1,
  },
  {
    id: 'vase',
    name: 'Fancy Vase',
    emoji: '🏺',
    category: 'ceramic',
    hitPoints: 2,
    satisfactionRating: 5,
    shardCount: 15,
    description: 'Expensive-looking. Extra satisfying.',
    color: '#c4785b',
    secondaryColor: '#d4956b',
    size: 'large',
    unlockLevel: 1,
  },
  {
    id: 'phone',
    name: 'Old Phone',
    emoji: '📱',
    category: 'electronic',
    hitPoints: 3,
    satisfactionRating: 5,
    shardCount: 10,
    description: 'That phone that always froze at the worst time.',
    color: '#333333',
    secondaryColor: '#1a73e8',
    size: 'small',
    unlockLevel: 2,
  },
  {
    id: 'laptop',
    name: 'Crappy Laptop',
    emoji: '💻',
    category: 'electronic',
    hitPoints: 5,
    satisfactionRating: 5,
    shardCount: 20,
    description: 'Blue screen of death? More like blue screen of DESTRUCTION.',
    color: '#555555',
    secondaryColor: '#3498db',
    size: 'large',
    unlockLevel: 3,
  },
  {
    id: 'bottle',
    name: 'Glass Bottle',
    emoji: '🍾',
    category: 'glass',
    hitPoints: 2,
    satisfactionRating: 4,
    shardCount: 14,
    description: 'Watch it explode into a thousand pieces.',
    color: '#2d5a27',
    secondaryColor: '#88ccff',
    size: 'medium',
    unlockLevel: 1,
  },
  {
    id: 'tv',
    name: 'Old CRT TV',
    emoji: '📺',
    category: 'electronic',
    hitPoints: 6,
    satisfactionRating: 5,
    shardCount: 25,
    description: 'Nothing but reruns anyway. Smash it!',
    color: '#444444',
    secondaryColor: '#222222',
    size: 'large',
    unlockLevel: 4,
  },
  {
    id: 'mug',
    name: 'Coffee Mug',
    emoji: '☕',
    category: 'ceramic',
    hitPoints: 1,
    satisfactionRating: 3,
    shardCount: 6,
    description: 'World\'s Best Boss? World\'s Best SMASH.',
    color: '#ffffff',
    secondaryColor: '#e74c3c',
    size: 'small',
    unlockLevel: 1,
  },
  {
    id: 'mirror',
    name: 'Mirror',
    emoji: '🪞',
    category: 'glass',
    hitPoints: 2,
    satisfactionRating: 4,
    shardCount: 18,
    description: '7 years bad luck? Worth it.',
    color: '#c0c0c0',
    secondaryColor: '#e8e8e8',
    size: 'large',
    unlockLevel: 2,
  },
  {
    id: 'guitar',
    name: 'Electric Guitar',
    emoji: '🎸',
    category: 'wood',
    hitPoints: 4,
    satisfactionRating: 5,
    shardCount: 12,
    description: 'Channel your inner rockstar. Smash it on stage!',
    color: '#8B4513',
    secondaryColor: '#d4a574',
    size: 'large',
    unlockLevel: 3,
  },
  {
    id: 'alarm_clock',
    name: 'Alarm Clock',
    emoji: '⏰',
    category: 'misc',
    hitPoints: 2,
    satisfactionRating: 5,
    shardCount: 8,
    description: 'For every early morning it ruined.',
    color: '#e74c3c',
    secondaryColor: '#f1c40f',
    size: 'small',
    unlockLevel: 2,
  },
  {
    id: 'printer',
    name: 'Office Printer',
    emoji: '🖨️',
    category: 'electronic',
    hitPoints: 7,
    satisfactionRating: 5,
    shardCount: 22,
    description: 'PC LOAD LETTER?! Die, printer, die!',
    color: '#cccccc',
    secondaryColor: '#333333',
    size: 'large',
    unlockLevel: 5,
  },
  {
    id: 'gnome',
    name: 'Garden Gnome',
    emoji: '🧙',
    category: 'ceramic',
    hitPoints: 3,
    satisfactionRating: 4,
    shardCount: 10,
    description: 'That creepy little guy had it coming.',
    color: '#e74c3c',
    secondaryColor: '#2ecc71',
    size: 'medium',
    unlockLevel: 2,
  },
  {
    id: 'watermelon',
    name: 'Watermelon',
    emoji: '🍉',
    category: 'misc',
    hitPoints: 1,
    satisfactionRating: 4,
    shardCount: 8,
    description: 'Gallagher style. Messy and glorious.',
    color: '#27ae60',
    secondaryColor: '#e74c3c',
    size: 'medium',
    unlockLevel: 1,
  },
  {
    id: 'piggy_bank',
    name: 'Piggy Bank',
    emoji: '🐷',
    category: 'ceramic',
    hitPoints: 2,
    satisfactionRating: 4,
    shardCount: 10,
    description: 'Break it open! (No actual money inside, sorry.)',
    color: '#ffb6c1',
    secondaryColor: '#ff69b4',
    size: 'small',
    unlockLevel: 2,
  },
];

export interface Tool {
  id: string;
  name: string;
  emoji: string;
  damage: number;
  speed: string;
}

export const TOOLS: Tool[] = [
  { id: 'fist', name: 'Bare Hands', emoji: '👊', damage: 1, speed: 'fast' },
  { id: 'hammer', name: 'Hammer', emoji: '🔨', damage: 2, speed: 'medium' },
  { id: 'bat', name: 'Baseball Bat', emoji: '🏏', damage: 3, speed: 'medium' },
  { id: 'sledge', name: 'Sledgehammer', emoji: '⚒️', damage: 5, speed: 'slow' },
];

export const CATEGORIES = [
  { id: 'all', name: 'All', emoji: '💥' },
  { id: 'glass', name: 'Glass', emoji: '🥃' },
  { id: 'ceramic', name: 'Ceramic', emoji: '🏺' },
  { id: 'electronic', name: 'Electronic', emoji: '📱' },
  { id: 'wood', name: 'Wood', emoji: '🪵' },
  { id: 'metal', name: 'Metal', emoji: '⚙️' },
  { id: 'misc', name: 'Misc', emoji: '🎲' },
];
